# Generated by Django 2.1.5 on 2019-02-13 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
